# Generated by Django 3.2.4 on 2021-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('link', models.URLField()),
                ('image_url', models.URLField()),
                ('pub_time', models.DateTimeField()),
            ],
        ),
    ]
