# Generated by Django 3.2.4 on 2021-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
