# Generated by Django 3.2.4 on 2021-06-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='f_rom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.client'),
            preserve_default=False,
        ),
    ]
