# Generated by Django 3.2.4 on 2021-06-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_message_f_rom'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
