# Generated by Django 3.2.4 on 2021-06-09 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('profiles', '0009_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='markets.market'),
            preserve_default=False,
        ),
    ]
