# Generated by Django 3.2.4 on 2021-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210610_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
