# Generated by Django 3.2.4 on 2021-06-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reponse',
            new_name='response',
        ),
    ]
