# Generated by Django 3.2.4 on 2021-06-10 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_rename_reponse_reply_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
