# Generated by Django 3.2.4 on 2021-06-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_reply_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='f_rom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='profiles.client'),
        ),
    ]
