# Generated by Django 3.2.4 on 2021-06-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_message_f_rom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='f_rom',
        ),
    ]
