# Generated by Django 3.2.4 on 2021-06-10 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0022_remove_message_f_rom'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='f_rom',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='users.customuser'),
            preserve_default=False,
        ),
    ]
