# Generated by Django 3.2.4 on 2021-06-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_message_f_rom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
