# Generated by Django 3.2.4 on 2021-06-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expertise',
        ),
    ]
