# Generated by Django 3.2.4 on 2021-06-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210608_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='experince',
            new_name='experience',
        ),
    ]
