# Generated by Django 3.2.4 on 2021-06-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_experince_customuser_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='expertise',
        ),
    ]
