# Generated by Django 3.2.4 on 2021-06-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('users', '0005_auto_20210609_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('interests', models.ManyToManyField(related_name='interested_investors', to='markets.Market')),
            ],
        ),
    ]
